version: '3.7'

services:
  #service 1: definition of mysql database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=springSecurity
      - MYSQL_ROOT_PASSWORD=son1808
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE


  #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: son1808



  #service 3: definition of spring-boot app
  appservice:
    image: spring-service
    container_name: app-service-spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/insurance_portal?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: son1808

